/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#444100',
        'on-surface': '#191c1b',
        'on-secondary-fixed-variant': '#394d0f',
        'inverse-on-surface': '#f0f1ee',
        'surface-container-highest': '#e2e3e0',
        'inverse-primary': '#a9cec3',
        secondary: '#506626',
        outline: '#717976',
        'on-background': '#191c1b',
        'secondary-fixed-dim': '#b6d083',
        'on-primary-fixed-variant': '#2a4d44',
        'surface-container': '#edeeeb',
        'on-error': '#ffffff',
        'surface-tint': '#42655c',
        'primary-fixed': '#c4ebde',
        'on-primary': '#ffffff',
        'surface-variant': '#e2e3e0',
        primary: '#173b33',
        'inverse-surface': '#2e312f',
        'on-surface-variant': '#414846',
        'on-secondary-fixed': '#131f00',
        'tertiary-container': '#b4b037',
        'surface-bright': '#f9faf7',
        'surface-container-high': '#e7e8e6',
        error: '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        tertiary: '#646100',
        'primary-container': '#2f5249',
        'primary-fixed-dim': '#a9cec3',
        'on-tertiary-fixed': '#1e1d00',
        'on-secondary-container': '#546a29',
        'tertiary-fixed-dim': '#d0cb50',
        'error-container': '#ffdad6',
        surface: '#f9faf7',
        'surface-dim': '#d9dad8',
        'on-error-container': '#93000a',
        'secondary-container': '#cfea9a',
        'on-tertiary-fixed-variant': '#4b4900',
        'on-primary-container': '#9ec4b8',
        'on-secondary': '#ffffff',
        background: '#f9faf7',
        'outline-variant': '#c1c8c4',
        'on-primary-fixed': '#00201a',
        'secondary-fixed': '#d2ec9d',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#ece769',
        'surface-container-low': '#f3f4f1',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'stack-md': '1rem',
        'stack-sm': '0.5rem',
        unit: '8px',
        'stack-lg': '2rem',
        'container-padding': '2.5rem',
        'section-margin': '5rem',
        'card-gap': '1.5rem',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-bold': ['"Plus Jakarta Sans"'],
        'button-text': ['"Plus Jakarta Sans"'],
        'headline-xl': ['"Plus Jakarta Sans"'],
        'headline-lg': ['"Plus Jakarta Sans"'],
        'body-md': ['"Plus Jakarta Sans"'],
        'body-lg': ['"Plus Jakarta Sans"'],
        'headline-md': ['"Plus Jakarta Sans"'],
      },
      fontSize: {
        'label-bold': ['14px', { lineHeight: '1.0', fontWeight: '700' }],
        'button-text': ['16px', { lineHeight: '1.0', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
      },
      keyframes: {
        blob: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
        },
      },
      animation: {
        blob: 'blob 7s infinite',
      },
    },
  },
  plugins: [],
};